### PR TITLE
Advertise services based on service names & not hostname

### PR DESCRIPTION
**Pull request by mtrudel**
This PR uses the service's configured name as the advertised name for the service, in place of the host-level name. This change affects PTR, TXT and SRV records only.

If one configures the library as so:

```
myhost# iex -S mix
iex(1)> MdnsLite.add_mdns_services(%{host: "My HTTP Service", protocol: "http", transport: "tcp", port: 8080})
:ok
```
and then in another window / machine, browses for services:
```
otherhost# dns-sd -B _http
Browsing for _http._tcp
DATE: ---Mon 16 Nov 2020---
16:25:36.214  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
16:25:36.214  Add        3   6 local.               _http._tcp.          Brother DCP-7065DN
16:25:36.214  Add        2   6 local.               _http._tcp.          myhost
^C
otherhost# dns-sd -L myhost http
Lookup myhost._http._tcp.local
DATE: ---Mon 16 Nov 2020---
16:36:54.346  ...STARTING...
16:36:54.347  myhost._http._tcp.local. can be reached at myhost.local.:8080 (interface 6)
```

This is incorrect; as can be seen from other advertised DNS-SD records the instance name is expected to be the human-friendly name of the service being advertised (ie: the value of the `name` field defined on the service). As currently implemented, mdns_lite uses the hostname as the advertised value, making the service name unused in the advertisement.

After applying the changes in this PR, we see expected behaviour:

```
myhost# iex -S mix
iex(1)> MdnsLite.add_mdns_services(%{host: "My HTTP Service", protocol: "http", transport: "tcp", port: 8080})
:ok
```
and then in another window / machine:
```
otherhost# dns-sd -B _http
Browsing for _http._tcp
DATE: ---Mon 16 Nov 2020---
16:25:36.214  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
16:25:36.214  Add        3   6 local.               _http._tcp.          Brother DCP-7065DN
16:25:36.214  Add        2   6 local.               _http._tcp.          My HTTP Service
^C
otherhost# dns-sd -L "My HTTP Service" http
Lookup My HTTP Service._http._tcp.local
DATE: ---Mon 16 Nov 2020---
16:36:54.346  ...STARTING...
16:36:54.347  My\032HTTP\032Service._http._tcp.local. can be reached at myhost.local.:8080 (interface 6)
```

Note that I was unable to successfully get the test suite running locally (either on macOS or on a Debian VM), so I'm not sure if there are any regressions there (though a quick read of the test suite suggests there are not).

### CODE REVIEW

**Comment by fhunleth** [comment]
@mtrudel Thanks for this update. Your comment is super helpful. 

I'm going to ping a few people to see if I can find someone to look at the test suite, but if nothing happens in the next day or so, I'll make a pass so that we can get this fix released.

**Comment by mtrudel** [comment]
It's curious that only one of the tests in the test matrix failed (and not in a way that I'd expect form this change). I wonder if it isn't a racy test that would pass on a re-run (I don't have the permissions to re-run the suite).

**Comment by fhunleth** [comment]
Yeah, I looked and I think it's the test.

This project technically doesn't have a maintainer. We use it a lot with Nerves, so we adopted it earlier this year. It needs some TLC, though. I posted about it on `nerves-dev`. Maybe someone will get a chance to fix the test. If nothing else, I'll have time tomorrow to take a look.

**Comment by mtrudel** [comment]
Updated to vintage_net 0.9.2 and tests are now green on macOS.

**Comment by ConnorRigby** [comment]
@fhunleth @mtrudel i ran the tests locally, and it worked for me no problem. I'm guessing there must be a race condition in the test suite?

**Review by ConnorRigby — APPROVED** [review]

**Comment by fhunleth** [comment]
I updated CI to use hexpm images and the Elixir 1.9 failure magically went away. Not super excited about that, but at least it's an old version of Elixir. 

I went ahead and manually merged the PR. https://github.com/nerves-networking/mdns_lite/commit/a9e597a6c3888a8b7fa2ecf6af7ff82384329ded

@mtrudel Thanks for the fix! @ConnorRigby Thanks for testing!

**Comment by mtrudel** [comment]
It appears that the functional change added in this PR was undone in #41 (which looks like it more or less rewrote the entire application, for the better). I'm looking at re-implementing this behaviour but it would seem to involve a fair bit of plumbing through service definitions, Options, and Table (possibly others too). Before I go to the effort I'm wondering if this omission was intentional @fhunleth?  

CC: @petermm

**Comment by fhunleth** [comment]
Thank you so much for looking up and quoting the relevant section of the RFC for this. 

I am on board with most of your proposal. My only change would be to keep using the hostname for the `instance_name`. I don't think that I can come up with a better name. For example, I'd prefer that "Nerves Device" isn't the default since `mdns_lite` should, in theory, work well in non-Nerves environments (I know, there are details, but I'd prefer to make it look less Nerves-only than more). If the default isn't "Nerves Device", then "MdnsLite User"? I can't think of anything good. Given that even Apple advertises the same string on mDNS that they use for their hostname on their laptops, I'm feeling like using the same string for both here isn't terrible. Perhaps it's a least bad default.

**Comment by mtrudel** [comment]
Sounds good! I think your suggestion is good (I agree that there's no good 'default' value for instance_name). I do think though that the instance_name field should be featured prominently in documentation with a strong suggestion (in the docs, not at runtime) that users override it where possible.

If this sounds good to you I can take a crack at implementing it up. LMK.

**Comment by mtrudel** [comment]
#53 fired up and ready to go

**Pull request closed without merging**
